# -*- coding: utf-8 -*-
"""decisiontree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFAHIaEZkyi4RxauF10pfiaFphGboTcg
"""

from sklearn import tree
import pandas as pd
import numpy as np

datasets = pd.read_csv('Dataset Iris.csv')

datasets.head()

datasets['Species'] = pd.factorize(datasets.Species)[0]

datasets.head()

datasets = datasets.drop(labels="Id", axis=1)

datasets.head()

datasets = datasets.to_numpy()

dataTraining = np.concatenate((datasets[0:40, :], datasets[50:90, :], datasets[100:140, :]), axis=0)
dataTesting = np.concatenate((datasets[40:50, :], datasets[90:100, :], datasets[140:150, :]), axis=0)

inputTrain = dataTraining[:, 0:4]
inputTest = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

model = tree.DecisionTreeClassifier()

model = model.fit(inputTrain, labelTraining)

hasilPrediksi = model.predict(inputTest)
print("Label Sebenarnya    : ", labelTesting)
print("Hasil Prediksi      : ", hasilPrediksi)

prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/ (prediksiBenar+prediksiSalah) * 100, "%")